//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSBLiving
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calculator
    {
      
        public string Code { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public string Weight { get; set; }
        public string isArchived { get; set; }
        public string SellPriceLn { get; set; }
        public string Region { get; set; }
    }
}
